/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#bec6e0",
        "surface-tint": "#565e74",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "on-primary": "#ffffff",
        "on-primary-container": "#7c839b",
        "inverse-surface": "#2d3133",
        "secondary-container": "#2170e4",
        "outline": "#76777d",
        "background": "#f7f9fb",
        "tertiary-container": "#07006c",
        "primary-container": "#131b2e",
        "primary-fixed-dim": "#bec6e0",
        "surface-dim": "#d8dadc",
        "surface": "#f7f9fb",
        "tertiary": "#000000",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#001a42",
        "on-tertiary-container": "#7073ff",
        "outline-variant": "#c6c6cd",
        "tertiary-fixed-dim": "#c0c1ff",
        "on-secondary": "#ffffff",
        "surface-container": "#eceef0",
        "secondary": "#0058be",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#e1e0ff",
        "secondary-fixed-dim": "#adc6ff",
        "on-primary-fixed-variant": "#3f465c",
        "on-background": "#191c1e",
        "on-surface": "#191c1e",
        "secondary-fixed": "#d8e2ff",
        "inverse-on-surface": "#eff1f3",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#004395",
        "primary-fixed": "#dae2fd",
        "on-tertiary-fixed": "#07006c",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#131b2e",
        "primary": "#000000",
        "on-secondary-container": "#fefcff",
        "on-surface-variant": "#45464d",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface-container-low": "#f2f4f6",
        "on-error": "#ffffff",
        "surface-variant": "#e0e3e5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "40px",
        "xs": "4px",
        "md": "24px",
        "xl": "64px",
        "sm": "12px",
        "base": "8px",
        "container-margin": "20px",
        "gutter": "16px"
      },
      fontFamily: {
        "title-lg": ["Inter"],
        "headline-md": ["Inter"],
        "display": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"]
      },
      fontSize: {
        "title-lg": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "display": ["42px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "1.25", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
